USER root
COPY configs/lxc/ca.crt /usr/lib/jvm/zulu11/lib/security
RUN \
	keytool -noprompt -trustcacerts -importcert \
		-alias project-cert \
		-storepass changeit \
		-cacerts \
		-file /usr/lib/jvm/zulu11/lib/security/ca.crt
USER liferay:liferay
