load('/repo/tilt/Tiltfile_functions', 'process_extension')

process_extension(
  'able-theme-css', 
  'client-extensions/able-theme-css',
  'extension_deployment',
  'dxp.localdev.me',
  objects=[
    'able-theme-css:ingress',
    'able-theme-css:ingressroute'
  ])