load('/repo/tilt/Tiltfile_functions', 'process_extension')

process_extension(
  'coupon-action-springboot', 
  'client-extensions/coupon-action-springboot',
  'extension_deployment',
  resource_deps=['coupon-definition'])
  