#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dxp-deployment
  labels:
    app: dxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dxp
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: dxp
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: dxp
          image: #@ data.values.image
          resources:
            limits:
              cpu: "4000m"
              memory: "8096Mi"
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 360
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          env:
            - name: LIFERAY_JPDA_ENABLED
              value: "true"
            - name: LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_VERIFY
              value: "false"
            - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_PROTOCOL
              value: https
            - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_ORG_PERIOD_APACHE_PERIOD_FELIX_PERIOD_CONFIGADMIN_PERIOD_PLUGIN_PERIOD_INTERPOLATION_PERIOD_SECRETSDIR
              value: /opt/liferay/osgi/configs,/var/run/secrets/kubernetes.io/serviceaccount
          ports:
            - containerPort: 8080
            - containerPort: 8000
            - containerPort: 11311