apiVersion: v1
kind: PersistentVolume
metadata:
  name: dxp-data
  labels:
    app: dxp
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /data/dxp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dxp-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi